In [1]:
import pandas as pd

In [5]:
df=pd.read_csv("millitakım.csv")
df

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
0,1,Harun Tekin,kaleci,17-6-1989,29,Bursa,"1,87 m",sağ ayak,2,NaN,2.5
1,23,Sinan Bolat,kaleci,3-9-1988,29,Royal FC,"1,88 m",sağ ayak,6,NaN,1.2
2,12,Serkan Kirintili,kaleci,15-2-1985,33,Konya,"1,86 m",sağ ayak,3,NaN,0.8
3,4,Caglar Söyüncü,stoper,23-5-1996,22,Sc Freiburg,"1,87 m",sağ ayak,16,1.0,18
4,22,Kaan Ayhan,stoper,10-11-1994,23,Düsseldorf,"1,85 m",sağ ayak,13,NaN,3
5,24,Ertugrul Ersoy,stoper,13-2-1997,21,Bursa,"1,87 m",sağ ayak,0,NaN,1.75
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
7,6,Ömer Bayram,sol bek,27-7-1991,26,Akhisar,"1,75 m",sol ayak,2,NaN,2
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
9,13,Zeki Celik,sağ bek,17-2-1997,21,İstanbul,"1,80 m",sağ ayak,1,NaN,0.8
10,5,Okay Yokuslu,önlibero,9-3-1994,24,Trabzon,"1,91 m",sağ ayak,14,1.0,7.50
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
12,14,Mahmut Tekdemir,önlibero,20-1-1988,30,Başakşehir,"1,78 m",sağ ayak,5,NaN,2
13,25,Tarkan Serbest,önlibero,19-4-1994,24,Austria Vien,"1,84 m",sağ ayak,1,NaN,1.5
14,8,Oguzhan Özyakup,orta saha,23-9-1992,25,Beşiktaş,"1,80 m",sağ ayak,35,1.0,8
15,11,Yusuf Yazici,on numara,29-1-1997,21,Trabzon,"1,83 m",sol ayak,9,NaN,12
16,19,Yunus Malli,on numara,24-2-1992,26,Wolsburg,"1,79 m",sağ ayak,18,1.0,9
17,20,Emre Akbaba,on numara,4-10-1992,25,Alanya,"1,80 m",cift ayakli,5,1.0,5.5
18,16,Deniz Türüc,on numara,29-1-1993,25,Kayseri,"1,75 m",sol ayak,2,NaN,3.5
19,21,Irfan Can Kahveci,on numara,15-7-1995,22,Başakşehir,"1,76 m",sol ayak,4,NaN,2.5
20,27,Berkay Özcan,on numara,15-2-1998,20,Stuttgart,"1,80 m",sağ ayak,1,NaN,2.5
21,18,Kenan Karaman,sol kanat,5-3-1994,24,Hannover,"1,89 m",sağ ayak,3,NaN,1.5
22,17,Cengiz Ünder,sağ kanat,14-7-1997,20,Roma,"1,73 m",sol ayak,11,4.0,27
23,7,Serdar Gürler,sağ kanat,14-9-1991,26,Osmanlı,"1,75 m",sağ ayak,4,NaN,3.5
24,10,Umut Bulut,santrafor,15-3-1983,35,Kayseri,"1,84 m",sağ ayak,39,10.0,0.45

In [6]:
df["Takım"]

0            Bursa
1         Royal FC
2            Konya
3      Sc Freiburg
4       Düsseldorf
5            Bursa
6       Fenerbahçe
7          Akhisar
8       Fenerbahçe
9         İstanbul
10         Trabzon
11      Fenerbahçe
12      Başakşehir
13    Austria Vien
14        Beşiktaş
15         Trabzon
16        Wolsburg
17          Alanya
18         Kayseri
19      Başakşehir
20       Stuttgart
21        Hannover
22            Roma
23        Osmanlı
24         Kayseri
Name: Takım, dtype: object

In [8]:
df["Takım"]=="Fenerbahçe"

0     False
1     False
2     False
3     False
4     False
5     False
6      True
7     False
8      True
9     False
10    False
11     True
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Takım, dtype: bool

In [9]:
takım=df["Takım"]=="Fenerbahçe"

In [10]:
df[takım]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5

In [11]:
df["Görev"]=="önlibero"

0     False
1     False
2     False
3     False
4     False
5     False
6     False
7     False
8     False
9     False
10     True
11     True
12     True
13     True
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24    False
Name: Görev, dtype: bool

In [12]:
ön=df["Görev"]=="önlibero"

In [13]:
df[ön]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
10,5,Okay Yokuslu,önlibero,9-3-1994,24,Trabzon,"1,91 m",sağ ayak,14,1.0,7.50
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
12,14,Mahmut Tekdemir,önlibero,20-1-1988,30,Başakşehir,"1,78 m",sağ ayak,5,NaN,2
13,25,Tarkan Serbest,önlibero,19-4-1994,24,Austria Vien,"1,84 m",sağ ayak,1,NaN,1.5

In [15]:
df[takım & ön]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5

In [19]:
yas=df["Yaş"]>25
yas

0      True
1      True
2      True
3     False
4     False
5     False
6      True
7      True
8      True
9     False
10    False
11     True
12     True
13    False
14    False
15    False
16     True
17    False
18    False
19    False
20    False
21    False
22    False
23     True
24     True
Name: Yaş, dtype: bool

In [20]:
df[yas]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
0,1,Harun Tekin,kaleci,17-6-1989,29,Bursa,"1,87 m",sağ ayak,2,NaN,2.5
1,23,Sinan Bolat,kaleci,3-9-1988,29,Royal FC,"1,88 m",sağ ayak,6,NaN,1.2
2,12,Serkan Kirintili,kaleci,15-2-1985,33,Konya,"1,86 m",sağ ayak,3,NaN,0.8
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
7,6,Ömer Bayram,sol bek,27-7-1991,26,Akhisar,"1,75 m",sol ayak,2,NaN,2
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
12,14,Mahmut Tekdemir,önlibero,20-1-1988,30,Başakşehir,"1,78 m",sağ ayak,5,NaN,2
16,19,Yunus Malli,on numara,24-2-1992,26,Wolsburg,"1,79 m",sağ ayak,18,1.0,9
23,7,Serdar Gürler,sağ kanat,14-9-1991,26,Osmanlı,"1,75 m",sağ ayak,4,NaN,3.5
24,10,Umut Bulut,santrafor,15-3-1983,35,Kayseri,"1,84 m",sağ ayak,39,10.0,0.45

In [21]:
df[yas|ön]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
0,1,Harun Tekin,kaleci,17-6-1989,29,Bursa,"1,87 m",sağ ayak,2,NaN,2.5
1,23,Sinan Bolat,kaleci,3-9-1988,29,Royal FC,"1,88 m",sağ ayak,6,NaN,1.2
2,12,Serkan Kirintili,kaleci,15-2-1985,33,Konya,"1,86 m",sağ ayak,3,NaN,0.8
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
7,6,Ömer Bayram,sol bek,27-7-1991,26,Akhisar,"1,75 m",sol ayak,2,NaN,2
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
10,5,Okay Yokuslu,önlibero,9-3-1994,24,Trabzon,"1,91 m",sağ ayak,14,1.0,7.50
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
12,14,Mahmut Tekdemir,önlibero,20-1-1988,30,Başakşehir,"1,78 m",sağ ayak,5,NaN,2
13,25,Tarkan Serbest,önlibero,19-4-1994,24,Austria Vien,"1,84 m",sağ ayak,1,NaN,1.5
16,19,Yunus Malli,on numara,24-2-1992,26,Wolsburg,"1,79 m",sağ ayak,18,1.0,9
23,7,Serdar Gürler,sağ kanat,14-9-1991,26,Osmanlı,"1,75 m",sağ ayak,4,NaN,3.5
24,10,Umut Bulut,santrafor,15-3-1983,35,Kayseri,"1,84 m",sağ ayak,39,10.0,0.45

In [23]:
df[yas & ön | takım]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
12,14,Mahmut Tekdemir,önlibero,20-1-1988,30,Başakşehir,"1,78 m",sağ ayak,5,NaN,2

In [24]:
df["Takım"]

0            Bursa
1         Royal FC
2            Konya
3      Sc Freiburg
4       Düsseldorf
5            Bursa
6       Fenerbahçe
7          Akhisar
8       Fenerbahçe
9         İstanbul
10         Trabzon
11      Fenerbahçe
12      Başakşehir
13    Austria Vien
14        Beşiktaş
15         Trabzon
16        Wolsburg
17          Alanya
18         Kayseri
19      Başakşehir
20       Stuttgart
21        Hannover
22            Roma
23        Osmanlı
24         Kayseri
Name: Takım, dtype: object

In [27]:
n=df["Takım"].isin(["Fenerbahçe","Kayseri"])

In [28]:
df[n]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
18,16,Deniz Türüc,on numara,29-1-1993,25,Kayseri,"1,75 m",sol ayak,2,NaN,3.5
24,10,Umut Bulut,santrafor,15-3-1983,35,Kayseri,"1,84 m",sağ ayak,39,10.0,0.45

In [29]:
df["Gol"]

0      NaN
1      NaN
2      NaN
3      1.0
4      NaN
5      NaN
6      NaN
7      NaN
8      NaN
9      NaN
10     1.0
11     2.0
12     NaN
13     NaN
14     1.0
15     NaN
16     1.0
17     1.0
18     NaN
19     NaN
20     NaN
21     NaN
22     4.0
23     NaN
24    10.0
Name: Gol, dtype: float64

In [30]:
df["Gol"].isnull()

0      True
1      True
2      True
3     False
4      True
5      True
6      True
7      True
8      True
9      True
10    False
11    False
12     True
13     True
14    False
15     True
16    False
17    False
18     True
19     True
20     True
21     True
22    False
23     True
24    False
Name: Gol, dtype: bool

In [32]:
null=df["Gol"].isnull()
null
df[null]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
0,1,Harun Tekin,kaleci,17-6-1989,29,Bursa,"1,87 m",sağ ayak,2,NaN,2.5
1,23,Sinan Bolat,kaleci,3-9-1988,29,Royal FC,"1,88 m",sağ ayak,6,NaN,1.2
2,12,Serkan Kirintili,kaleci,15-2-1985,33,Konya,"1,86 m",sağ ayak,3,NaN,0.8
4,22,Kaan Ayhan,stoper,10-11-1994,23,Düsseldorf,"1,85 m",sağ ayak,13,NaN,3
5,24,Ertugrul Ersoy,stoper,13-2-1997,21,Bursa,"1,87 m",sağ ayak,0,NaN,1.75
6,3,Hasan Ali Kaldirim,sol bek,9-12-1989,28,Fenerbahçe,"1,83 m",sol ayak,25,NaN,3.25
7,6,Ömer Bayram,sol bek,27-7-1991,26,Akhisar,"1,75 m",sol ayak,2,NaN,2
8,2,Sener Özbayrakli,sağ bek,23-1-1990,28,Fenerbahçe,"1,71 m",sağ ayak,17,NaN,2
9,13,Zeki Celik,sağ bek,17-2-1997,21,İstanbul,"1,80 m",sağ ayak,1,NaN,0.8
12,14,Mahmut Tekdemir,önlibero,20-1-1988,30,Başakşehir,"1,78 m",sağ ayak,5,NaN,2
13,25,Tarkan Serbest,önlibero,19-4-1994,24,Austria Vien,"1,84 m",sağ ayak,1,NaN,1.5
15,11,Yusuf Yazici,on numara,29-1-1997,21,Trabzon,"1,83 m",sol ayak,9,NaN,12
18,16,Deniz Türüc,on numara,29-1-1993,25,Kayseri,"1,75 m",sol ayak,2,NaN,3.5
19,21,Irfan Can Kahveci,on numara,15-7-1995,22,Başakşehir,"1,76 m",sol ayak,4,NaN,2.5
20,27,Berkay Özcan,on numara,15-2-1998,20,Stuttgart,"1,80 m",sağ ayak,1,NaN,2.5
21,18,Kenan Karaman,sol kanat,5-3-1994,24,Hannover,"1,89 m",sağ ayak,3,NaN,1.5
23,7,Serdar Gürler,sağ kanat,14-9-1991,26,Osmanlı,"1,75 m",sağ ayak,4,NaN,3.5

In [33]:
notnull=df["Gol"].notnull()

In [34]:
df[notnull]

,Numara,İsim,Görev,Doğum Tarihi,Yaş,Takım,Boy,Ayak,Maç,Gol,Milyon Euro
3,4,Caglar Söyüncü,stoper,23-5-1996,22,Sc Freiburg,"1,87 m",sağ ayak,16,1.0,18
10,5,Okay Yokuslu,önlibero,9-3-1994,24,Trabzon,"1,91 m",sağ ayak,14,1.0,7.50
11,15,Mehmet Topal,önlibero,3-3-1986,32,Fenerbahçe,"1,87 m",cift ayakli,78,2.0,2.5
14,8,Oguzhan Özyakup,orta saha,23-9-1992,25,Beşiktaş,"1,80 m",sağ ayak,35,1.0,8
16,19,Yunus Malli,on numara,24-2-1992,26,Wolsburg,"1,79 m",sağ ayak,18,1.0,9
17,20,Emre Akbaba,on numara,4-10-1992,25,Alanya,"1,80 m",cift ayakli,5,1.0,5.5
22,17,Cengiz Ünder,sağ kanat,14-7-1997,20,Roma,"1,73 m",sol ayak,11,4.0,27
24,10,Umut Bulut,santrafor,15-3-1983,35,Kayseri,"1,84 m",sağ ayak,39,10.0,0.45